<a href="https://colab.research.google.com/github/cx666321/--/blob/main/Test3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


숙제 1
**굵은 텍스트**


In [9]:
import numpy as np

# 用于存储 3 次彩票结果的列表
lotto_list = []

# 为了保证每次结果不同，但可复现，设置不同的随机种子
np.random.seed(85)

for i in range(3):
    # 生成 1~45 的数组
    numbers = np.arange(1, 46)

    # 随机打乱数组
    np.random.shuffle(numbers)

    # 取前 6 个作为一次彩票结果
    lotto = numbers[:6]

    # 将 NumPy 数组转换为列表并存储
    lotto_list.append(lotto.tolist())

# 将列表转换为 NumPy 二维数组
lotto_array = np.array(lotto_list)

# 输出结果
print("3 次彩票结果构成的二维数组：")
print(lotto_array)

print("数组形状：", lotto_array.shape)


3 次彩票结果构成的二维数组：
[[22  9 15 44 39 37]
 [ 7 31 24 40 11 16]
 [ 8  3 23 40 38 32]]
数组形状： (3, 6)


**숙제 2**

In [10]:
# 1. 导入 numpy 库并命名为 np
import numpy as np

# ===============================
# 一、创建随机三维数组（示例参考）
# ===============================

# 指定三维数组的大小
shape_example = (3, 4, 5)

# 创建一个三维数组，元素范围 0~9
arr_example = np.random.randint(0, 10, shape_example)

# 打印三维数组
print("示例三维数组 (3, 4, 5)：")
print(arr_example)


# =========================================
# 二、创建形状为 (3, 3, 6) 的随机三维数组
# =========================================

# 指定三维数组形状
shape_3d = (3, 3, 6)

# 创建随机三维数组，元素范围 0~20
arr_3d = np.random.randint(0, 21, shape_3d)

# 打印结果
print("\n随机三维数组 (3, 3, 6)，元素范围 0~20：")
print(arr_3d)


# =====================================
# 三、创建形状为 (5, 6) 的随机二维数组
# =====================================

# 指定二维数组形状
shape_2d = (5, 6)

# 创建随机二维数组，元素范围 0~100
arr_2d = np.random.randint(0, 101, shape_2d)

# 打印结果
print("\n随机二维数组 (5, 6)，元素范围 0~100：")
print(arr_2d)


示例三维数组 (3, 4, 5)：
[[[6 5 5 1 3]
  [0 4 3 0 9]
  [2 5 3 1 4]
  [9 5 8 5 8]]

 [[1 4 1 9 2]
  [0 9 2 4 8]
  [9 8 0 9 6]
  [4 9 8 3 7]]

 [[6 2 4 7 4]
  [3 4 3 1 5]
  [8 3 9 7 8]
  [0 8 9 5 1]]]

随机三维数组 (3, 3, 6)，元素范围 0~20：
[[[ 8 13 13  2 12 12]
  [14 16  7 14 18  6]
  [15  5  4 13 17  3]]

 [[14 13 17  4 14  4]
  [19  5 11  7 12 11]
  [13  0 13  7 10 18]]

 [[10  3 18 17  8 11]
  [12 17  9  5  8  1]
  [ 1 17 18  1  4 14]]]

随机二维数组 (5, 6)，元素范围 0~100：
[[51 34 54  2 79 46]
 [38 46 43 29  8 89]
 [46 17 48 16 78 72]
 [94 44 17  0 23 97]
 [54 54 80 75  4 65]]


**숙제 3**

In [12]:

# 1. 导入 numpy 库并命名为 np
import numpy as np

# 2. 使用 arange 创建一维数组 temp
temp = np.arange(48)

print("一维数组 temp：")
print(temp)
print("temp 的形状：", temp.shape)


# =====================================
# 3. 使用 reshape 创建三维数组 (4, 3, 4)
# =====================================

arr_3d = temp.reshape(4, 3, 4)

print("\n三维数组 arr_3d (4, 3, 4)：")
print(arr_3d)
print("arr_3d 的形状：", arr_3d.shape)


# =====================================
# 4. 使用 reshape 创建二维数组 (6, 8)
# =====================================

arr_2d = temp.reshape(6, 8)

print("\n二维数组 arr_2d (6, 8)：")
print(arr_2d)
print("arr_2d 的形状：", arr_2d.shape)


一维数组 temp：
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47]
temp 的形状： (48,)

三维数组 arr_3d (4, 3, 4)：
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]

 [[36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]
arr_3d 的形状： (4, 3, 4)

二维数组 arr_2d (6, 8)：
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]]
arr_2d 的形状： (6, 8)
